databases:
  - name: 
    databaseName: 
    user: 
    region: singapore

services:
  - type: web
    name: rails7-sample-staging
    env: ruby
    region: singapore
    plan: free
    buildCommand: "render-build.sh"
    startCommand: "bundle exec ruby app.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7_sample_staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
