databases:
  - name: render_app
    databaseName:render_app_0l3u
    user:syy
    region: singapore

services:
  - type: web
    name: render_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "render-build.sh"
    startCommand: "bundle exec ruby app.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7_sample_staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
